# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = D:/CMake/bin/cmake.exe

# The command to remove a file.
RM = D:/CMake/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:/CH58X-CMake-master/CH58X-CMake-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:/CH58X-CMake-master/CH58X-CMake-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:/CMake/bin/cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:/CMake/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:/CH58X-CMake-master/CH58X-CMake-master/CMakeFiles D:/CH58X-CMake-master/CH58X-CMake-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:/CH58X-CMake-master/CH58X-CMake-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ch58x-ninja.elf

# Build rule for target.
ch58x-ninja.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ch58x-ninja.elf
.PHONY : ch58x-ninja.elf

# fast build rule for target.
ch58x-ninja.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/build
.PHONY : ch58x-ninja.elf/fast

APP/Main.obj: APP/Main.c.obj
.PHONY : APP/Main.obj

# target to build an object file
APP/Main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/Main.c.obj
.PHONY : APP/Main.c.obj

APP/Main.i: APP/Main.c.i
.PHONY : APP/Main.i

# target to preprocess a source file
APP/Main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/Main.c.i
.PHONY : APP/Main.c.i

APP/Main.s: APP/Main.c.s
.PHONY : APP/Main.s

# target to generate assembly for a file
APP/Main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/Main.c.s
.PHONY : APP/Main.c.s

APP/broadcast.obj: APP/broadcast.c.obj
.PHONY : APP/broadcast.obj

# target to build an object file
APP/broadcast.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/broadcast.c.obj
.PHONY : APP/broadcast.c.obj

APP/broadcast.i: APP/broadcast.c.i
.PHONY : APP/broadcast.i

# target to preprocess a source file
APP/broadcast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/broadcast.c.i
.PHONY : APP/broadcast.c.i

APP/broadcast.s: APP/broadcast.c.s
.PHONY : APP/broadcast.s

# target to generate assembly for a file
APP/broadcast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/broadcast.c.s
.PHONY : APP/broadcast.c.s

APP/devinfoservice.obj: APP/devinfoservice.c.obj
.PHONY : APP/devinfoservice.obj

# target to build an object file
APP/devinfoservice.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/devinfoservice.c.obj
.PHONY : APP/devinfoservice.c.obj

APP/devinfoservice.i: APP/devinfoservice.c.i
.PHONY : APP/devinfoservice.i

# target to preprocess a source file
APP/devinfoservice.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/devinfoservice.c.i
.PHONY : APP/devinfoservice.c.i

APP/devinfoservice.s: APP/devinfoservice.c.s
.PHONY : APP/devinfoservice.s

# target to generate assembly for a file
APP/devinfoservice.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/APP/devinfoservice.c.s
.PHONY : APP/devinfoservice.c.s

Dependency/HAL/KEY.obj: Dependency/HAL/KEY.c.obj
.PHONY : Dependency/HAL/KEY.obj

# target to build an object file
Dependency/HAL/KEY.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/KEY.c.obj
.PHONY : Dependency/HAL/KEY.c.obj

Dependency/HAL/KEY.i: Dependency/HAL/KEY.c.i
.PHONY : Dependency/HAL/KEY.i

# target to preprocess a source file
Dependency/HAL/KEY.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/KEY.c.i
.PHONY : Dependency/HAL/KEY.c.i

Dependency/HAL/KEY.s: Dependency/HAL/KEY.c.s
.PHONY : Dependency/HAL/KEY.s

# target to generate assembly for a file
Dependency/HAL/KEY.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/KEY.c.s
.PHONY : Dependency/HAL/KEY.c.s

Dependency/HAL/LED.obj: Dependency/HAL/LED.c.obj
.PHONY : Dependency/HAL/LED.obj

# target to build an object file
Dependency/HAL/LED.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/LED.c.obj
.PHONY : Dependency/HAL/LED.c.obj

Dependency/HAL/LED.i: Dependency/HAL/LED.c.i
.PHONY : Dependency/HAL/LED.i

# target to preprocess a source file
Dependency/HAL/LED.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/LED.c.i
.PHONY : Dependency/HAL/LED.c.i

Dependency/HAL/LED.s: Dependency/HAL/LED.c.s
.PHONY : Dependency/HAL/LED.s

# target to generate assembly for a file
Dependency/HAL/LED.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/LED.c.s
.PHONY : Dependency/HAL/LED.c.s

Dependency/HAL/MCU.obj: Dependency/HAL/MCU.c.obj
.PHONY : Dependency/HAL/MCU.obj

# target to build an object file
Dependency/HAL/MCU.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/MCU.c.obj
.PHONY : Dependency/HAL/MCU.c.obj

Dependency/HAL/MCU.i: Dependency/HAL/MCU.c.i
.PHONY : Dependency/HAL/MCU.i

# target to preprocess a source file
Dependency/HAL/MCU.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/MCU.c.i
.PHONY : Dependency/HAL/MCU.c.i

Dependency/HAL/MCU.s: Dependency/HAL/MCU.c.s
.PHONY : Dependency/HAL/MCU.s

# target to generate assembly for a file
Dependency/HAL/MCU.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/MCU.c.s
.PHONY : Dependency/HAL/MCU.c.s

Dependency/HAL/RTC.obj: Dependency/HAL/RTC.c.obj
.PHONY : Dependency/HAL/RTC.obj

# target to build an object file
Dependency/HAL/RTC.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/RTC.c.obj
.PHONY : Dependency/HAL/RTC.c.obj

Dependency/HAL/RTC.i: Dependency/HAL/RTC.c.i
.PHONY : Dependency/HAL/RTC.i

# target to preprocess a source file
Dependency/HAL/RTC.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/RTC.c.i
.PHONY : Dependency/HAL/RTC.c.i

Dependency/HAL/RTC.s: Dependency/HAL/RTC.c.s
.PHONY : Dependency/HAL/RTC.s

# target to generate assembly for a file
Dependency/HAL/RTC.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/RTC.c.s
.PHONY : Dependency/HAL/RTC.c.s

Dependency/HAL/SLEEP.obj: Dependency/HAL/SLEEP.c.obj
.PHONY : Dependency/HAL/SLEEP.obj

# target to build an object file
Dependency/HAL/SLEEP.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/SLEEP.c.obj
.PHONY : Dependency/HAL/SLEEP.c.obj

Dependency/HAL/SLEEP.i: Dependency/HAL/SLEEP.c.i
.PHONY : Dependency/HAL/SLEEP.i

# target to preprocess a source file
Dependency/HAL/SLEEP.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/SLEEP.c.i
.PHONY : Dependency/HAL/SLEEP.c.i

Dependency/HAL/SLEEP.s: Dependency/HAL/SLEEP.c.s
.PHONY : Dependency/HAL/SLEEP.s

# target to generate assembly for a file
Dependency/HAL/SLEEP.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/HAL/SLEEP.c.s
.PHONY : Dependency/HAL/SLEEP.c.s

Dependency/RVMSIS/core_riscv.obj: Dependency/RVMSIS/core_riscv.c.obj
.PHONY : Dependency/RVMSIS/core_riscv.obj

# target to build an object file
Dependency/RVMSIS/core_riscv.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/RVMSIS/core_riscv.c.obj
.PHONY : Dependency/RVMSIS/core_riscv.c.obj

Dependency/RVMSIS/core_riscv.i: Dependency/RVMSIS/core_riscv.c.i
.PHONY : Dependency/RVMSIS/core_riscv.i

# target to preprocess a source file
Dependency/RVMSIS/core_riscv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/RVMSIS/core_riscv.c.i
.PHONY : Dependency/RVMSIS/core_riscv.c.i

Dependency/RVMSIS/core_riscv.s: Dependency/RVMSIS/core_riscv.c.s
.PHONY : Dependency/RVMSIS/core_riscv.s

# target to generate assembly for a file
Dependency/RVMSIS/core_riscv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/RVMSIS/core_riscv.c.s
.PHONY : Dependency/RVMSIS/core_riscv.c.s

Dependency/Startup/startup_CH583.obj: Dependency/Startup/startup_CH583.S.obj
.PHONY : Dependency/Startup/startup_CH583.obj

# target to build an object file
Dependency/Startup/startup_CH583.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/Startup/startup_CH583.S.obj
.PHONY : Dependency/Startup/startup_CH583.S.obj

Dependency/StdPeriphDriver/CH58x_adc.obj: Dependency/StdPeriphDriver/CH58x_adc.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_adc.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_adc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_adc.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_adc.c.obj

Dependency/StdPeriphDriver/CH58x_adc.i: Dependency/StdPeriphDriver/CH58x_adc.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_adc.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_adc.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_adc.c.i

Dependency/StdPeriphDriver/CH58x_adc.s: Dependency/StdPeriphDriver/CH58x_adc.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_adc.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_adc.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_adc.c.s

Dependency/StdPeriphDriver/CH58x_clk.obj: Dependency/StdPeriphDriver/CH58x_clk.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_clk.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_clk.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_clk.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_clk.c.obj

Dependency/StdPeriphDriver/CH58x_clk.i: Dependency/StdPeriphDriver/CH58x_clk.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_clk.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_clk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_clk.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_clk.c.i

Dependency/StdPeriphDriver/CH58x_clk.s: Dependency/StdPeriphDriver/CH58x_clk.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_clk.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_clk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_clk.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_clk.c.s

Dependency/StdPeriphDriver/CH58x_flash.obj: Dependency/StdPeriphDriver/CH58x_flash.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_flash.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_flash.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_flash.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_flash.c.obj

Dependency/StdPeriphDriver/CH58x_flash.i: Dependency/StdPeriphDriver/CH58x_flash.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_flash.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_flash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_flash.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_flash.c.i

Dependency/StdPeriphDriver/CH58x_flash.s: Dependency/StdPeriphDriver/CH58x_flash.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_flash.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_flash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_flash.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_flash.c.s

Dependency/StdPeriphDriver/CH58x_gpio.obj: Dependency/StdPeriphDriver/CH58x_gpio.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_gpio.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_gpio.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_gpio.c.obj

Dependency/StdPeriphDriver/CH58x_gpio.i: Dependency/StdPeriphDriver/CH58x_gpio.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_gpio.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_gpio.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_gpio.c.i

Dependency/StdPeriphDriver/CH58x_gpio.s: Dependency/StdPeriphDriver/CH58x_gpio.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_gpio.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_gpio.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_gpio.c.s

Dependency/StdPeriphDriver/CH58x_i2c.obj: Dependency/StdPeriphDriver/CH58x_i2c.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_i2c.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_i2c.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_i2c.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_i2c.c.obj

Dependency/StdPeriphDriver/CH58x_i2c.i: Dependency/StdPeriphDriver/CH58x_i2c.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_i2c.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_i2c.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_i2c.c.i

Dependency/StdPeriphDriver/CH58x_i2c.s: Dependency/StdPeriphDriver/CH58x_i2c.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_i2c.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_i2c.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_i2c.c.s

Dependency/StdPeriphDriver/CH58x_pwm.obj: Dependency/StdPeriphDriver/CH58x_pwm.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_pwm.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_pwm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_pwm.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_pwm.c.obj

Dependency/StdPeriphDriver/CH58x_pwm.i: Dependency/StdPeriphDriver/CH58x_pwm.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_pwm.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_pwm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_pwm.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_pwm.c.i

Dependency/StdPeriphDriver/CH58x_pwm.s: Dependency/StdPeriphDriver/CH58x_pwm.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_pwm.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_pwm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_pwm.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_pwm.c.s

Dependency/StdPeriphDriver/CH58x_pwr.obj: Dependency/StdPeriphDriver/CH58x_pwr.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_pwr.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_pwr.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_pwr.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_pwr.c.obj

Dependency/StdPeriphDriver/CH58x_pwr.i: Dependency/StdPeriphDriver/CH58x_pwr.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_pwr.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_pwr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_pwr.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_pwr.c.i

Dependency/StdPeriphDriver/CH58x_pwr.s: Dependency/StdPeriphDriver/CH58x_pwr.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_pwr.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_pwr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_pwr.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_pwr.c.s

Dependency/StdPeriphDriver/CH58x_spi0.obj: Dependency/StdPeriphDriver/CH58x_spi0.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_spi0.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_spi0.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_spi0.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_spi0.c.obj

Dependency/StdPeriphDriver/CH58x_spi0.i: Dependency/StdPeriphDriver/CH58x_spi0.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_spi0.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_spi0.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_spi0.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_spi0.c.i

Dependency/StdPeriphDriver/CH58x_spi0.s: Dependency/StdPeriphDriver/CH58x_spi0.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_spi0.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_spi0.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_spi0.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_spi0.c.s

Dependency/StdPeriphDriver/CH58x_spi1.obj: Dependency/StdPeriphDriver/CH58x_spi1.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_spi1.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_spi1.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_spi1.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_spi1.c.obj

Dependency/StdPeriphDriver/CH58x_spi1.i: Dependency/StdPeriphDriver/CH58x_spi1.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_spi1.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_spi1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_spi1.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_spi1.c.i

Dependency/StdPeriphDriver/CH58x_spi1.s: Dependency/StdPeriphDriver/CH58x_spi1.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_spi1.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_spi1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_spi1.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_spi1.c.s

Dependency/StdPeriphDriver/CH58x_sys.obj: Dependency/StdPeriphDriver/CH58x_sys.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_sys.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_sys.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_sys.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_sys.c.obj

Dependency/StdPeriphDriver/CH58x_sys.i: Dependency/StdPeriphDriver/CH58x_sys.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_sys.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_sys.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_sys.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_sys.c.i

Dependency/StdPeriphDriver/CH58x_sys.s: Dependency/StdPeriphDriver/CH58x_sys.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_sys.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_sys.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_sys.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_sys.c.s

Dependency/StdPeriphDriver/CH58x_timer0.obj: Dependency/StdPeriphDriver/CH58x_timer0.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer0.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_timer0.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer0.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer0.c.obj

Dependency/StdPeriphDriver/CH58x_timer0.i: Dependency/StdPeriphDriver/CH58x_timer0.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer0.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_timer0.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer0.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer0.c.i

Dependency/StdPeriphDriver/CH58x_timer0.s: Dependency/StdPeriphDriver/CH58x_timer0.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer0.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_timer0.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer0.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer0.c.s

Dependency/StdPeriphDriver/CH58x_timer1.obj: Dependency/StdPeriphDriver/CH58x_timer1.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer1.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_timer1.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer1.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer1.c.obj

Dependency/StdPeriphDriver/CH58x_timer1.i: Dependency/StdPeriphDriver/CH58x_timer1.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer1.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_timer1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer1.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer1.c.i

Dependency/StdPeriphDriver/CH58x_timer1.s: Dependency/StdPeriphDriver/CH58x_timer1.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer1.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_timer1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer1.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer1.c.s

Dependency/StdPeriphDriver/CH58x_timer2.obj: Dependency/StdPeriphDriver/CH58x_timer2.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer2.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_timer2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer2.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer2.c.obj

Dependency/StdPeriphDriver/CH58x_timer2.i: Dependency/StdPeriphDriver/CH58x_timer2.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer2.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_timer2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer2.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer2.c.i

Dependency/StdPeriphDriver/CH58x_timer2.s: Dependency/StdPeriphDriver/CH58x_timer2.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer2.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_timer2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer2.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer2.c.s

Dependency/StdPeriphDriver/CH58x_timer3.obj: Dependency/StdPeriphDriver/CH58x_timer3.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer3.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_timer3.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer3.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_timer3.c.obj

Dependency/StdPeriphDriver/CH58x_timer3.i: Dependency/StdPeriphDriver/CH58x_timer3.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer3.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_timer3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer3.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_timer3.c.i

Dependency/StdPeriphDriver/CH58x_timer3.s: Dependency/StdPeriphDriver/CH58x_timer3.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer3.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_timer3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_timer3.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_timer3.c.s

Dependency/StdPeriphDriver/CH58x_uart0.obj: Dependency/StdPeriphDriver/CH58x_uart0.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart0.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_uart0.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart0.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart0.c.obj

Dependency/StdPeriphDriver/CH58x_uart0.i: Dependency/StdPeriphDriver/CH58x_uart0.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart0.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_uart0.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart0.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart0.c.i

Dependency/StdPeriphDriver/CH58x_uart0.s: Dependency/StdPeriphDriver/CH58x_uart0.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart0.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_uart0.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart0.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart0.c.s

Dependency/StdPeriphDriver/CH58x_uart1.obj: Dependency/StdPeriphDriver/CH58x_uart1.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart1.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_uart1.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart1.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart1.c.obj

Dependency/StdPeriphDriver/CH58x_uart1.i: Dependency/StdPeriphDriver/CH58x_uart1.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart1.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_uart1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart1.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart1.c.i

Dependency/StdPeriphDriver/CH58x_uart1.s: Dependency/StdPeriphDriver/CH58x_uart1.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart1.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_uart1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart1.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart1.c.s

Dependency/StdPeriphDriver/CH58x_uart2.obj: Dependency/StdPeriphDriver/CH58x_uart2.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart2.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_uart2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart2.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart2.c.obj

Dependency/StdPeriphDriver/CH58x_uart2.i: Dependency/StdPeriphDriver/CH58x_uart2.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart2.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_uart2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart2.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart2.c.i

Dependency/StdPeriphDriver/CH58x_uart2.s: Dependency/StdPeriphDriver/CH58x_uart2.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart2.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_uart2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart2.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart2.c.s

Dependency/StdPeriphDriver/CH58x_uart3.obj: Dependency/StdPeriphDriver/CH58x_uart3.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart3.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_uart3.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart3.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_uart3.c.obj

Dependency/StdPeriphDriver/CH58x_uart3.i: Dependency/StdPeriphDriver/CH58x_uart3.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart3.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_uart3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart3.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_uart3.c.i

Dependency/StdPeriphDriver/CH58x_uart3.s: Dependency/StdPeriphDriver/CH58x_uart3.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart3.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_uart3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_uart3.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_uart3.c.s

Dependency/StdPeriphDriver/CH58x_usb2dev.obj: Dependency/StdPeriphDriver/CH58x_usb2dev.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2dev.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_usb2dev.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2dev.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2dev.c.obj

Dependency/StdPeriphDriver/CH58x_usb2dev.i: Dependency/StdPeriphDriver/CH58x_usb2dev.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2dev.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_usb2dev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2dev.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2dev.c.i

Dependency/StdPeriphDriver/CH58x_usb2dev.s: Dependency/StdPeriphDriver/CH58x_usb2dev.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2dev.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_usb2dev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2dev.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2dev.c.s

Dependency/StdPeriphDriver/CH58x_usb2hostBase.obj: Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostBase.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.obj

Dependency/StdPeriphDriver/CH58x_usb2hostBase.i: Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostBase.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.i

Dependency/StdPeriphDriver/CH58x_usb2hostBase.s: Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostBase.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostBase.c.s

Dependency/StdPeriphDriver/CH58x_usb2hostClass.obj: Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostClass.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.obj

Dependency/StdPeriphDriver/CH58x_usb2hostClass.i: Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostClass.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.i

Dependency/StdPeriphDriver/CH58x_usb2hostClass.s: Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostClass.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usb2hostClass.c.s

Dependency/StdPeriphDriver/CH58x_usbdev.obj: Dependency/StdPeriphDriver/CH58x_usbdev.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usbdev.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_usbdev.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbdev.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usbdev.c.obj

Dependency/StdPeriphDriver/CH58x_usbdev.i: Dependency/StdPeriphDriver/CH58x_usbdev.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usbdev.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_usbdev.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbdev.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usbdev.c.i

Dependency/StdPeriphDriver/CH58x_usbdev.s: Dependency/StdPeriphDriver/CH58x_usbdev.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usbdev.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_usbdev.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbdev.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usbdev.c.s

Dependency/StdPeriphDriver/CH58x_usbhostBase.obj: Dependency/StdPeriphDriver/CH58x_usbhostBase.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostBase.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_usbhostBase.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbhostBase.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostBase.c.obj

Dependency/StdPeriphDriver/CH58x_usbhostBase.i: Dependency/StdPeriphDriver/CH58x_usbhostBase.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostBase.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_usbhostBase.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbhostBase.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostBase.c.i

Dependency/StdPeriphDriver/CH58x_usbhostBase.s: Dependency/StdPeriphDriver/CH58x_usbhostBase.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostBase.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_usbhostBase.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbhostBase.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostBase.c.s

Dependency/StdPeriphDriver/CH58x_usbhostClass.obj: Dependency/StdPeriphDriver/CH58x_usbhostClass.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostClass.obj

# target to build an object file
Dependency/StdPeriphDriver/CH58x_usbhostClass.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbhostClass.c.obj
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostClass.c.obj

Dependency/StdPeriphDriver/CH58x_usbhostClass.i: Dependency/StdPeriphDriver/CH58x_usbhostClass.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostClass.i

# target to preprocess a source file
Dependency/StdPeriphDriver/CH58x_usbhostClass.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbhostClass.c.i
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostClass.c.i

Dependency/StdPeriphDriver/CH58x_usbhostClass.s: Dependency/StdPeriphDriver/CH58x_usbhostClass.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostClass.s

# target to generate assembly for a file
Dependency/StdPeriphDriver/CH58x_usbhostClass.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/StdPeriphDriver/CH58x_usbhostClass.c.s
.PHONY : Dependency/StdPeriphDriver/CH58x_usbhostClass.c.s

Dependency/USB_LIB/CH583UFI.obj: Dependency/USB_LIB/CH583UFI.c.obj
.PHONY : Dependency/USB_LIB/CH583UFI.obj

# target to build an object file
Dependency/USB_LIB/CH583UFI.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/USB_LIB/CH583UFI.c.obj
.PHONY : Dependency/USB_LIB/CH583UFI.c.obj

Dependency/USB_LIB/CH583UFI.i: Dependency/USB_LIB/CH583UFI.c.i
.PHONY : Dependency/USB_LIB/CH583UFI.i

# target to preprocess a source file
Dependency/USB_LIB/CH583UFI.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/USB_LIB/CH583UFI.c.i
.PHONY : Dependency/USB_LIB/CH583UFI.c.i

Dependency/USB_LIB/CH583UFI.s: Dependency/USB_LIB/CH583UFI.c.s
.PHONY : Dependency/USB_LIB/CH583UFI.s

# target to generate assembly for a file
Dependency/USB_LIB/CH583UFI.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/USB_LIB/CH583UFI.c.s
.PHONY : Dependency/USB_LIB/CH583UFI.c.s

Dependency/printf/printf.obj: Dependency/printf/printf.c.obj
.PHONY : Dependency/printf/printf.obj

# target to build an object file
Dependency/printf/printf.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/printf/printf.c.obj
.PHONY : Dependency/printf/printf.c.obj

Dependency/printf/printf.i: Dependency/printf/printf.c.i
.PHONY : Dependency/printf/printf.i

# target to preprocess a source file
Dependency/printf/printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/printf/printf.c.i
.PHONY : Dependency/printf/printf.c.i

Dependency/printf/printf.s: Dependency/printf/printf.c.s
.PHONY : Dependency/printf/printf.s

# target to generate assembly for a file
Dependency/printf/printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ch58x-ninja.elf.dir/build.make CMakeFiles/ch58x-ninja.elf.dir/Dependency/printf/printf.c.s
.PHONY : Dependency/printf/printf.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ch58x-ninja.elf"
	@echo "... APP/Main.obj"
	@echo "... APP/Main.i"
	@echo "... APP/Main.s"
	@echo "... APP/broadcast.obj"
	@echo "... APP/broadcast.i"
	@echo "... APP/broadcast.s"
	@echo "... APP/devinfoservice.obj"
	@echo "... APP/devinfoservice.i"
	@echo "... APP/devinfoservice.s"
	@echo "... Dependency/HAL/KEY.obj"
	@echo "... Dependency/HAL/KEY.i"
	@echo "... Dependency/HAL/KEY.s"
	@echo "... Dependency/HAL/LED.obj"
	@echo "... Dependency/HAL/LED.i"
	@echo "... Dependency/HAL/LED.s"
	@echo "... Dependency/HAL/MCU.obj"
	@echo "... Dependency/HAL/MCU.i"
	@echo "... Dependency/HAL/MCU.s"
	@echo "... Dependency/HAL/RTC.obj"
	@echo "... Dependency/HAL/RTC.i"
	@echo "... Dependency/HAL/RTC.s"
	@echo "... Dependency/HAL/SLEEP.obj"
	@echo "... Dependency/HAL/SLEEP.i"
	@echo "... Dependency/HAL/SLEEP.s"
	@echo "... Dependency/RVMSIS/core_riscv.obj"
	@echo "... Dependency/RVMSIS/core_riscv.i"
	@echo "... Dependency/RVMSIS/core_riscv.s"
	@echo "... Dependency/Startup/startup_CH583.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_adc.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_adc.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_adc.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_clk.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_clk.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_clk.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_flash.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_flash.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_flash.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_gpio.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_gpio.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_gpio.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_i2c.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_i2c.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_i2c.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_pwm.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_pwm.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_pwm.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_pwr.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_pwr.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_pwr.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_spi0.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_spi0.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_spi0.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_spi1.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_spi1.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_spi1.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_sys.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_sys.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_sys.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer0.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer0.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer0.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer1.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer1.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer1.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer2.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer2.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer2.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer3.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer3.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_timer3.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart0.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart0.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart0.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart1.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart1.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart1.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart2.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart2.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart2.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart3.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart3.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_uart3.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2dev.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2dev.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2dev.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2hostBase.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2hostBase.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2hostBase.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2hostClass.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2hostClass.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_usb2hostClass.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbdev.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbdev.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbdev.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbhostBase.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbhostBase.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbhostBase.s"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbhostClass.obj"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbhostClass.i"
	@echo "... Dependency/StdPeriphDriver/CH58x_usbhostClass.s"
	@echo "... Dependency/USB_LIB/CH583UFI.obj"
	@echo "... Dependency/USB_LIB/CH583UFI.i"
	@echo "... Dependency/USB_LIB/CH583UFI.s"
	@echo "... Dependency/printf/printf.obj"
	@echo "... Dependency/printf/printf.i"
	@echo "... Dependency/printf/printf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

